# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "alpine"
            python: "3.7"
          - platform: "alpine"
            python: "3.8.0"
          - platform: "alpine"
            python: "3.8"
          - platform: "alpine"
            python: "3.9"
          - platform: "alpine"
            python: "3.10"
          - platform: "alpine"
            python: "3.11"
          - platform: "alpine"
            python: "3.12"
          - platform: "alpine"
            python: "3.13"
          - platform: "alpine"
            python: "3.14"

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build local image ${{ matrix.alpine }}
      run: docker build --build-arg PYTHON_VERSION="${{ matrix.python }}" -t "tests-${{ matrix.platform }}-py${{ matrix.python }}" -f Dockerfile--${{ matrix.platform }}.tmpl .
    - name: Run
      run: docker run -t "tests-${{ matrix.platform }}-py${{ matrix.python }}"
