# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Verification

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "alpine"
            python: "3.7"
          - platform: "alpine"
            python: "3.8.0"
          - platform: "alpine"
            python: "3.8"
          - platform: "alpine"
            python: "3.9"
          - platform: "alpine"
            python: "3.10"
          - platform: "alpine"
            python: "3.11"
          - platform: "alpine"
            python: "3.12"
          - platform: "alpine"
            python: "3.13"
          - platform: "alpine"
            python: "3.14"

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build local image ${{ matrix.alpine }}
      run: docker build --build-arg PYTHON_VERSION="${{ matrix.python }}" -t "tests-${{ matrix.platform }}-py${{ matrix.python }}" -f Dockerfile--${{ matrix.platform }}.tmpl .
    - name: Prepare logs folder on the host
      run: mkdir -p "logs-${{ matrix.platform }}-py${{ matrix.python }}"
    - name: Adjust logs folder permission
      run: chmod -R 777 "logs-${{ matrix.platform }}-py${{ matrix.python }}"
    - name: Run
      run: docker run -t -v ${{ github.workspace }}/logs-${{ matrix.platform }}-py${{ matrix.python }}:/home/test/testgres/logs "tests-${{ matrix.platform }}-py${{ matrix.python }}"
    - name: Upload Logs
      uses: actions/upload-artifact@v4
      if: always() # IT IS IMPORTANT!
      with:
        name: container-logs--${{ matrix.platform }}-py${{ matrix.python }}
        path: "logs-${{ matrix.platform }}-py${{ matrix.python }}/"
        retention-days: 90
